"use client";

import { useEffect, useRef, useState } from "react";
import {
  AlertCircle,
  AlertTriangle,
  CheckCircle2,
  Loader2,
  Mic,
  MicOff,
  RefreshCw,
  Square,
  ClipboardList
} from "lucide-react";
import ClinicalDashboard from "./clinical-dashboard";

// ── Types ───────────────────────────────────────────────────────────────────

type Status = "idle" | "recording" | "processing" | "complete" | "error";

interface ClinicalReport {
  transcript_accuracy_assessment: string;
  overall_articulation_quality: string;
  flagged_words: {
    word: string;
    ctc_confidence: number;
    clinical_interpretation: string;
  }[];
  prosody_evaluation: string;
  max_silent_pause_note: string;
  motor_tremor_assessment: string;
  detected_events: {
    event_type: string;
    target_word: string;
    clinical_note: string;
  }[];
  dysarthria_detected: boolean;
  dysarthria_severity?: string | null;
  severity_rationale: string;
  confidence_in_assessment: string;
  primary_deficit_summary: string;
  disclaimer: string;
  recommended_exercises: string[];
}

// Pipeline phases — text advances via timeouts, but completion is gated
// entirely on the real network response resolving. No hard 20s cutoff.
interface Phase {
  delayMs: number;
  text: string;
}

const PIPELINE_PHASES: Phase[] = [
  { delayMs: 0, text: "Transcribing audio via Whisper ASR..." },
  { delayMs: 4000, text: "Aligning phonetic timestamps..." },
  { delayMs: 8000, text: "Extracting DSP motor tremor envelopes..." },
  { delayMs: 14000, text: "Generating Gemini clinical report..." },
];

const API_URL = "http://127.0.0.1:8000/analyze";
const MOCK_API = true; // Set to false to hit the real FastAPI backend

// ── Network layer ───────────────────────────────────────────────────────────

async function analyzeAudio(
  blob: Blob,
  text: string,
  signal: AbortSignal
): Promise<ClinicalReport> {
  if (MOCK_API) {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve({
          dysarthria_detected: true,
          severity: "Mild-to-Moderate",
          dysarthria_severity: "Mild-to-Moderate",
          confidence_in_assessment: "High",
          transcript_accuracy_assessment: "Whisper produced a nearly perfect transcript with minor omissions at the boundary.",
          overall_articulation_quality: "Articulation is generally intelligible but shows notable slurring on plosives.",
          flagged_words: [
            { word: "grandfather", ctc_confidence: -1.85, clinical_interpretation: "Slurred velar plosive." },
            { word: "swiftly", ctc_confidence: -2.10, clinical_interpretation: "Imprecise fricative cluster." }
          ],
          prosody_evaluation: "Speaking rate is 92 WPM, which is below the healthy norm of 130 WPM.",
          max_silent_pause_note: "Max silent pause was 0.8s, indicating potential respiratory weakness or word finding difficulty.",
          motor_tremor_assessment: "Mild DSP tremor detected during the onset of complex syllables.",
          detected_events: [
            { event_type: "within_word_tremor", target_word: "nearly", clinical_note: "Tremor envelope detected on vowel." }
          ],
          primary_deficit_summary: "Hypokinetic dysarthria with mild articulatory imprecision.",
          severity_rationale: "The combination of slow WPM and low CTC scores on complex consonants indicates mild-to-moderate impairment.",
          disclaimer: "This automated assessment is generated by NeuroClear AI and is intended to assist, not replace, the clinical judgment of a qualified Speech-Language Pathologist.",
          recommended_exercises: []
        } as unknown as ClinicalReport);
      }, 2500); // 2.5 second delay
    });
  }

  const formData = new FormData();
  formData.append("target_text", text);
  // FastAPI requires a filename to correctly interpret the file field
  formData.append("audio_file", blob, "session.webm");

  const response = await fetch(API_URL, {
    method: "POST",
    body: formData,
    signal, // AbortController signal for race-condition safety on unmount
  });

  if (!response.ok) {
    // Try to read the backend's error detail; fall back to a generic message
    let detail = `Server error ${response.status}`;
    try {
      const body = await response.json();
      detail = body.detail ?? detail;
    } catch {
      // response body was not JSON — use the status text
      detail = response.statusText || detail;
    }
    throw new Error(detail);
  }

  return response.json() as Promise<ClinicalReport>;
}

// ── Component ───────────────────────────────────────────────────────────────

export default function ScreeningInterface({ passages }: { passages: string[] }) {
  const [targetText, setTargetText] = useState<string>("");
  const [status, setStatus] = useState<Status>("idle");
  const [audioBlob, setAudioBlob] = useState<Blob | null>(null);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [loadingText, setLoadingText] = useState<string>("");
  const [resultData, setResultData] = useState<ClinicalReport | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Mic-error is kept separate from the pipeline error state so the inline
  // banner and the full error-card don't clobber each other
  const [micError, setMicError] = useState<string | null>(null);

  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const chunksRef = useRef<Blob[]>([]);
  const streamRef = useRef<MediaStream | null>(null);
  const maxRecordingTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // AbortController lets us cancel the fetch if the component unmounts
  const abortControllerRef = useRef<AbortController | null>(null);

  // ── Random sentence selection on mount ──────────────────────────────────

  useEffect(() => {
    const randomIndex = Math.floor(Math.random() * passages.length);
    setTargetText(passages[randomIndex]);
  }, [passages]);

  // ── Cleanup object URL on unmount / change ───────────────────────────────

  useEffect(() => {
    return () => {
      if (audioUrl) URL.revokeObjectURL(audioUrl);
    };
  }, [audioUrl]);

  // ── Abort any in-flight fetch on unmount ─────────────────────────────────

  useEffect(() => {
    return () => {
      abortControllerRef.current?.abort();
    };
  }, []);

  // ── Recording ────────────────────────────────────────────────────────────

  async function startRecording() {
    setMicError(null);
    setErrorMessage(null);
    chunksRef.current = [];

    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      streamRef.current = stream;

      const recorder = new MediaRecorder(stream);
      mediaRecorderRef.current = recorder;

      recorder.ondataavailable = (e: BlobEvent) => {
        if (e.data.size > 0) chunksRef.current.push(e.data);
      };

      recorder.onstop = () => {
        const blob = new Blob(chunksRef.current, { type: "audio/webm" });
        const url = URL.createObjectURL(blob);
        setAudioBlob(blob);
        setAudioUrl(url);

        // Release the browser's red microphone indicator immediately
        streamRef.current?.getTracks().forEach((t) => t.stop());

        setStatus("processing");
      };

      recorder.start();
      setStatus("recording");

      // Start the 60-second safety cutoff
      maxRecordingTimerRef.current = setTimeout(() => {
        console.log("60-second max limit reached. Auto-stopping...");
        stopRecording();
      }, 60000);
    } catch (err) {
      const message =
        err instanceof DOMException && err.name === "NotAllowedError"
          ? "Microphone access was denied. Please allow microphone permissions and try again."
          : "Could not access your microphone. Please check your device settings.";
      setMicError(message);
    }
  }

  function stopRecording() {
    if (maxRecordingTimerRef.current) {
      clearTimeout(maxRecordingTimerRef.current);
    }
    mediaRecorderRef.current?.stop();
    // onstop fires → blob is ready → status becomes "processing"
  }

  // ── Phased loading text + real network call ───────────────────────────────
  //
  // When status becomes "processing" we:
  //   1. Schedule the phase-text animations (no forced completion timeout).
  //   2. Fire the real fetch with an AbortController for unmount safety.
  //   3. On success  → set resultData + "complete".
  //   4. On error    → set errorMessage + "error".

  useEffect(() => {
    if (status !== "processing") return;
    if (!audioBlob || !targetText) return;

    // ── Phase text timers (no completion timer — that's the network's job) ──
    const timers: ReturnType<typeof setTimeout>[] = [];
    PIPELINE_PHASES.forEach(({ delayMs, text }) => {
      timers.push(setTimeout(() => setLoadingText(text), delayMs));
    });

    // ── Real fetch ──────────────────────────────────────────────────────────
    const controller = new AbortController();
    abortControllerRef.current = controller;

    analyzeAudio(audioBlob, targetText, controller.signal)
      .then((data: ClinicalReport) => {
        // Log the raw payload for debugging
        console.log("Gemini Output:", data);

        // Cache the exercises in localStorage for the Progress Tracker page
        try {
          localStorage.setItem(
            "neuroclear_exercises",
            JSON.stringify(data.recommended_exercises ?? [])
          );
        } catch {
          // localStorage unavailable in some environments — non-fatal
        }

        setResultData(data);
        setStatus("complete");
      })
      .catch((err: unknown) => {
        // Ignore errors from intentional AbortController cancellation
        if (err instanceof DOMException && err.name === "AbortError") return;

        const message =
          err instanceof Error
            ? err.message
            : "An unexpected error occurred during analysis.";
        setErrorMessage(message);
        setStatus("error");
      });

    return () => {
      timers.forEach(clearTimeout);
      controller.abort(); // cancel the fetch if status changes before it resolves
    };
  }, [status, audioBlob, targetText]);

  // ── Reset ─────────────────────────────────────────────────────────────────

  function reset() {
    abortControllerRef.current?.abort();
    if (audioUrl) URL.revokeObjectURL(audioUrl);

    setStatus("idle");
    setAudioBlob(null);
    setAudioUrl(null);
    setLoadingText("");
    setResultData(null);
    setErrorMessage(null);
    setMicError(null);
    chunksRef.current = [];

    // Pick a new passage for the next session
    const randomIndex = Math.floor(Math.random() * passages.length);
    setTargetText(passages[randomIndex]);
  }

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <div className="flex w-full flex-col items-center gap-6">

      {/* ── Target sentence card ───────────────────────────────────────────── */}
      <div className="w-full max-w-lg rounded-xl border border-blue-100 bg-blue-50 px-5 py-4 shadow-sm">
        <p className="mb-2 text-xs font-bold uppercase tracking-wider text-blue-600">
          Read this passage aloud
        </p>
        <p className="text-base font-medium leading-relaxed text-blue-950">
          {targetText ? `"${targetText}"` : "Loading passage..."}
        </p>
      </div>

      {/* ── Status card ───────────────────────────────────────────────────── */}
      <div className="relative w-full max-w-lg overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">

        {/* Top accent bar — colour tracks status */}
        <div
          className={`h-1 w-full transition-all duration-700 ${status === "idle"
            ? "bg-gray-200"
            : status === "recording"
              ? "animate-pulse bg-red-500"
              : status === "processing"
                ? "bg-brand-500"
                : status === "complete"
                  ? "bg-emerald-500"
                  : /* error */ "bg-amber-500"
            }`}
        />

        <div className="flex flex-col items-center gap-6 px-8 py-10">

          {/* ── Idle ──────────────────────────────────────────────────────── */}
          {status === "idle" && (
            <>
              <div className="flex h-20 w-20 items-center justify-center rounded-full border-2 border-gray-200 bg-gray-50">
                <Mic className="h-8 w-8 text-gray-400" />
              </div>
              <div className="text-center">
                <p className="text-lg font-semibold text-gray-800">
                  Ready to record
                </p>
                <p className="mt-1 text-sm text-gray-500">
                  Press the button below, then read the target sentence aloud.
                </p>
              </div>
              <button
                onClick={startRecording}
                className="
                  inline-flex items-center gap-2 rounded-xl bg-brand-600
                  px-6 py-3 text-sm font-semibold text-white shadow-md
                  shadow-brand-600/25 transition-all duration-200
                  hover:bg-brand-700 hover:shadow-lg hover:shadow-brand-600/30
                  active:scale-95
                "
              >
                <Mic className="h-4 w-4" />
                Start Recording
              </button>
            </>
          )}

          {/* ── Recording ─────────────────────────────────────────────────── */}
          {status === "recording" && (
            <>
              <div className="relative flex h-20 w-20 items-center justify-center">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-red-400 opacity-30" />
                <div className="relative flex h-20 w-20 items-center justify-center rounded-full border-2 border-red-500 bg-red-50">
                  <Mic className="h-8 w-8 text-red-500" />
                </div>
              </div>
              <div className="text-center">
                <p className="text-lg font-semibold text-red-600">
                  Recording…
                </p>
                <p className="mt-1 text-sm text-gray-500">
                  Speak clearly. Auto-stops after 60 seconds.
                </p>
              </div>
              <button
                onClick={stopRecording}
                className="
                  inline-flex items-center gap-2 rounded-xl bg-red-600
                  px-6 py-3 text-sm font-semibold text-white shadow-md
                  shadow-red-600/25 transition-all duration-200
                  hover:bg-red-700 active:scale-95
                "
              >
                <Square className="h-4 w-4 fill-white" />
                Stop &amp; Analyze
              </button>
            </>
          )}

          {/* ── Processing ────────────────────────────────────────────────── */}
          {status === "processing" && (
            <>
              <div className="flex h-20 w-20 items-center justify-center rounded-full border-2 border-brand-200 bg-brand-50">
                <Loader2 className="h-8 w-8 animate-spin text-brand-600" />
              </div>
              <div className="text-center">
                <p className="text-lg font-semibold text-gray-800">
                  Analyzing your speech
                </p>
                <p className="mt-2 min-h-[20px] text-sm font-medium text-brand-600 transition-all duration-500">
                  {loadingText}
                </p>
              </div>

              {/* Live pipeline checklist */}
              <div className="flex w-full max-w-xs flex-col gap-2">
                {PIPELINE_PHASES.map(({ text }) => {
                  const currentIndex = PIPELINE_PHASES.findIndex(
                    (p) => p.text === loadingText
                  );
                  const stepIndex = PIPELINE_PHASES.findIndex(
                    (p) => p.text === text
                  );
                  const done = stepIndex < currentIndex;
                  const active = stepIndex === currentIndex;

                  return (
                    <div key={text} className="flex items-center gap-3">
                      <div
                        className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-full border text-[10px] font-bold transition-all duration-300 ${done
                          ? "border-brand-500 bg-brand-500 text-white"
                          : active
                            ? "border-brand-500 bg-white text-brand-600"
                            : "border-gray-200 bg-gray-50 text-gray-400"
                          }`}
                      >
                        {done ? "✓" : stepIndex + 1}
                      </div>
                      <span
                        className={`text-xs transition-colors duration-300 ${done
                          ? "text-brand-600 line-through opacity-60"
                          : active
                            ? "font-semibold text-gray-800"
                            : "text-gray-400"
                          }`}
                      >
                        {text}
                      </span>
                    </div>
                  );
                })}
              </div>
            </>
          )}

          {/* ── Complete ──────────────────────────────────────────────────── */}
          {status === "complete" && resultData && (
            <>
              <div className={`flex h-20 w-20 items-center justify-center rounded-full border-2 ${
                resultData.dysarthria_detected 
                  ? "border-blue-500 bg-blue-50" 
                  : "border-emerald-500 bg-emerald-50"
              }`}>
                {resultData.dysarthria_detected ? (
                  <ClipboardList className="h-9 w-9 text-blue-500" /> 
                ) : (
                  <CheckCircle2 className="h-9 w-9 text-emerald-500" />
                )}
              </div>
              <div className="text-center">
                <p className="text-lg font-semibold text-gray-800">
                  Analysis Complete
                </p>
                <p className="mt-1 text-sm text-gray-500">
                  Your clinical report is ready. Navigate to{" "}
                  <span className="font-medium text-brand-600">
                    Diagnostic Report
                  </span>{" "}
                  to review the results.
                </p>
              </div>

              {/* Quick result summary if we have the data */}
              {resultData && (
                <div
                  className={`w-full rounded-xl border px-4 py-3 ${resultData.dysarthria_detected
                    ? "border-red-200 bg-red-50"
                    : "border-emerald-100 bg-emerald-50"
                    }`}
                >
                  <p
                    className={`text-xs font-semibold uppercase tracking-wider ${resultData.dysarthria_detected ? "text-red-700" : "text-emerald-700"
                      }`}
                  >
                    Dysarthria detected:{" "}
                    <span
                      className={
                        resultData.dysarthria_detected
                          ? "text-red-600"
                          : "text-emerald-600"
                      }
                    >
                      {resultData.dysarthria_detected ? "Yes" : "No"}
                    </span>
                  </p>
                  {resultData.dysarthria_severity && (
                    <p
                      className={`mt-0.5 text-xs ${resultData.dysarthria_detected ? "text-red-700" : "text-emerald-700"
                        }`}
                    >
                      Severity: <span className="font-medium">{resultData.dysarthria_severity}</span>
                    </p>
                  )}
                </div>
              )}

              {/* Audio playback */}
              {audioUrl && (
                <div className="w-full rounded-xl border border-gray-200 bg-gray-50 p-4">
                  <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-gray-500">
                    Session Recording
                  </p>
                  <audio controls src={audioUrl} className="w-full rounded-lg" />
                  <p className="mt-2 text-[11px] text-gray-400">
                    {audioBlob
                      ? `File size: ${(audioBlob.size / 1024).toFixed(1)} KB`
                      : null}
                  </p>
                </div>
              )}



              <button
                onClick={reset}
                className="
                  inline-flex items-center gap-2 rounded-xl border border-gray-200
                  bg-white px-6 py-3 text-sm font-semibold text-gray-700
                  shadow-sm transition-all duration-200 hover:border-gray-300
                  hover:bg-gray-50 active:scale-95
                "
              >
                <MicOff className="h-4 w-4" />
                Record New Session
              </button>
            </>
          )}

          {/* ── Error (pipeline / network failure) ───────────────────────── */}
          {status === "error" && (
            <>
              <div className="flex h-20 w-20 items-center justify-center rounded-full border-2 border-amber-400 bg-amber-50">
                <AlertTriangle className="h-9 w-9 text-amber-500" />
              </div>
              <div className="text-center">
                <p className="text-lg font-semibold text-gray-800">
                  Analysis Failed
                </p>
                <p className="mt-1 text-sm text-gray-500">
                  The pipeline could not complete your session.
                </p>
              </div>

              {/* Error detail card */}
              <div className="w-full rounded-xl border border-amber-200 bg-amber-50 px-4 py-3">
                <div className="flex items-start gap-2">
                  <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
                  <div>
                    <p className="text-xs font-semibold text-amber-800">
                      Backend Error
                    </p>
                    <p className="mt-0.5 text-xs text-amber-700">
                      {errorMessage ?? "An unexpected error occurred."}
                    </p>
                  </div>
                </div>
              </div>

              <div className="flex gap-3">
                {/* Retry — reuses the existing blob + text, re-fires the fetch */}
                <button
                  onClick={() => {
                    setErrorMessage(null);
                    setStatus("processing");
                  }}
                  className="
                    inline-flex items-center gap-2 rounded-xl bg-brand-600
                    px-5 py-2.5 text-sm font-semibold text-white shadow-md
                    shadow-brand-600/25 transition-all duration-200
                    hover:bg-brand-700 active:scale-95
                  "
                >
                  <RefreshCw className="h-4 w-4" />
                  Retry Analysis
                </button>

                {/* Full reset — starts a completely new session */}
                <button
                  onClick={reset}
                  className="
                    inline-flex items-center gap-2 rounded-xl border border-gray-200
                    bg-white px-5 py-2.5 text-sm font-semibold text-gray-700
                    shadow-sm transition-all duration-200 hover:border-gray-300
                    hover:bg-gray-50 active:scale-95
                  "
                >
                  <MicOff className="h-4 w-4" />
                  New Session
                </button>
              </div>
            </>
          )}

        </div>
      </div>

      {/* ── MOUNT THE NEW CLINICAL DASHBOARD HERE (OUTSIDE THE STATUS CARD) ── */}
      {status === "complete" && resultData && (
        <ClinicalDashboard report={resultData} />
      )}
      {/* ─────────────────────────────────────────────────────────────────── */}

      {/* ── Microphone permission error banner (only shown in idle) ─────────── */}
      {micError && (
        <div className="flex w-full items-start gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3">
          <AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-red-500" />
          <div>
            <p className="text-sm font-semibold text-red-700">
              Microphone Error
            </p>
            <p className="mt-0.5 text-sm text-red-600">{micError}</p>
          </div>
        </div>
      )}
    </div>
  );
}
